# Generated by Django 4.2.6 on 2024-05-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentwordindex',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
