# Generated by Django 4.2.6 on 2024-05-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0003_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='meta',
            field=models.TextField(blank=True),
        ),
    ]
